Compile aptos-node package separately (#16)
https://github.com/shinamicorp/aptos-docker/pull/13 incorrectly changed
how `aptos-node` is compiled, causing the following error

```
thread 'main' panicked at aptos-move/aptos-vm/src/natives.rs:189:5:
aptos-node was compiled with feature flags that shouldn't be enabled.
This is caused by cargo's feature unification.
When you compile two crates with a shared dependency, if one enables a feature flag for the dependency, then it is also enabled for the other crate.
PLEASE RECOMPILE APTOS-NODE SEPARATELY using the following command:
    cargo build --package aptos-node
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```